#1.표준 토큰화

자연어 처리에 사용되는 대표적인 파이썬 패키지(영문)->NLTK가 있다. 해당 패키지는 Copurs,Creat Token, 형태소 분석, 품사 태깅 등을 제공한다

1.1 표준 토큰화

표준 토큰화 중 하나인 Treebank 표준 토큰화를 사용하는 방법

In [ ]:
from nltk.tokenize import TreebankWordTokenizer #표준화 단어 tokenizer 불러옴
tokenizer = TreebankWordTokenizer()
text = "Model-based RL don't need a value function for the policy"
print(tokenizer.tokenize(text))

['Model-based', 'RL', 'do', "n't", 'need', 'a', 'value', 'function', 'for', 'the', 'policy']


1.2 토큰화 라이브러리

Treebank 토큰화 이외에도 NLTk 패키지에는 여러 종류의 토큰화 패키지가 있습니다. 예를 들면 아래와 같은 word_tokenizer

In [ ]:
!pip install nltk

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [13]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [14]:
from nltk.tokenize import word_tokenize
print(word_tokenize(text))


['Model-based', 'RL', 'do', "n't", 'need', 'a', 'value', 'function', 'for', 'the', 'policy']


정제 및 추출

#2.어간 추출 및 표제어 추출
단어의 형태소 level에서 분석을 하게 되면 다른 품사 또는 다른 시제의 단어라고 해도 같은 형태로 토큰화를 할 수 있다. 어간 추출 하는 방법

2.1 어간 추출(Stemmer) VS 표제어 추출(Lemmatizer)

대표적인 어간 추출(stemming) 기법인 Porter 및 Lancaster 추출 패키지를 불러오고, 이를 활용하는 방법 결과를 보고 어간 추출 기반 기법의 문제점 파악

내가 생각하는 문제점? : 어간을 제대로 추출해내지 못함
LancasterStemmer는 그래도 ate를 제외하곤 제대로 추출하였지만
PorterStemmer는 그러하지 못함

어간 추출

In [16]:
from nltk.stem import PorterStemmer, LancasterStemmer
stem1 = PorterStemmer()
stem2 = LancasterStemmer()
words = ["eat","ate","eaten","eating"]
print("PorterStemmer :", [stem1.stem(w) for w in words]) #poterstemmer을 w에 변수를 poterstemmer를 이용하고 반복문을 이용하여 리스트에 있는 단어를 하나씩 꺼내서 추출
print("LancasterStemmer :", [stem2.stem(w) for w in words])

PorterStemmer : ['eat', 'ate', 'eaten', 'eat']
LancasterStemmer : ['eat', 'at', 'eat', 'eat']


표제어 추출

In [22]:
import nltk

nltk.download('wordnet')


[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [39]:
import nltk
nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to /root/nltk_data...


True

In [40]:
from nltk import WordNetLemmatizer
lemm = WordNetLemmatizer()
words = ["eat","ate","eaten","eating"]
print("WordNetLemmatizer :", [lemm.lemmatize(w, pos ="v")for w in words]) #pos를 통해 동사를 품사태깅 한다.

WordNetLemmatizer : ['eat', 'eat', 'eat', 'eat']


#3.불용어 제거

영어에서의 불용어 중 예시 몇 가지를 확인 하는 방법. 마지막 줄의 숫자를 증가시키면 볼 수 있는 단어의 수가 증가한다. 마찬가지로 stopword 단어 데이터를 받기 위한 작업이 필요함

In [45]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
print(stopwords.words('english')[:10])

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [46]:
!pip install Konlpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 44.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 465.6/465.6 KB 37.8 MB/s eta 0:00:00


In [55]:
import nltk
nltk.download('punkt')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

input_sentence = "We should all study hard for the exam"
stop_words = set(stopwords.words('english'))
word_tokens = word_tokenize(input_sentence)
result =[]
for w in word_tokens: # <- 토큰화 결과에 대해서
  if w not in stop_words:   #<- we부터 해서 쭉쭉 빼서 오는데 일단 we를 stop_words에 있나 구분하고 없으면 결과에 추가한다.
    result.append(w)
print(word_tokens)
print(result)

# 각 단어마다 불용어 목록에 있으면 포함 하고 없으면 포함하지 말자는 코드

['We', 'should', 'all', 'study', 'hard', 'for', 'the', 'exam']
['We', 'study', 'hard', 'exam']


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


#4.정수 인코딩 및 sorting
4.1 Enumerate

In [67]:
list = ["English",'math','Science']
for n, name in enumerate(list): #n은 순서 name은 값 Enumerate를 사용하면 키와 값을 한번에 볼수 있다.
  print("Course : {}, Number : {}".format(name, n))

Course : English, Number : 0
Course : math, Number : 1
Course : Science, Number : 2


4.2 정수 인코딩 및 High-frequency Sorting

In [68]:
vocab={'apple':2, 'july' : 6, 'piano' : 4} #bow(단어마다 문장 빈도수 apple은 2번 나왔고 july은 6번 나왔고 ... 다는 말)
vocab_sort = sorted(vocab.items(), key = lambda x:x[1],reverse = True) #lambda는 임수 함수 -> 한번만 사용하고 만다 x:x[1]을 리턴한다 reverse= 내림차순 (큰->작)
print(vocab_sort)
word2inx = {word[0] : index + 1 for index, word in enumerate(vocab_sort)} #word[0] -> vocab에서 문자를 의미 word[1]을 하면 값을 의미 함 그 후 인덱스를 하나씩 증가하면서 
print(word2inx)

[('july', 6), ('piano', 4), ('apple', 2)]
{'july': 1, 'piano': 2, 'apple': 3}


BoW로 만들어진 토큰화의 결과를 가장 높은 빈도수부터 재정렬하고, 이를 통해 정수 인코딩을 하는 과정

In [76]:
from IPython.core.inputtransformer2 import tokenize
from nltk.tokenize import TreebankWordTokenizer
tokenizer = TreebankWordTokenizer()
text = "Model-based RL don't need a value function for the policy,"\
       "but some of Model-based RL algorithms do have a value function. "
token_text = tokenizer.tokenize(text) #여기 까지 토큰 리스트를 생성
word2inx = {} #dic값을 저장
Bow = [] #list값을 저장
for word in token_text: #토큰화 된 단어 마다
  if word not in word2inx.keys(): # 만약 word2inx dic에 키값에 단어가 없으면 순서대로 왔다 했을 때 model이 오니깐 키는 없음
      word2inx[word] = len(word2inx) #그럼 word2inx[modle] = len(wordinx) -> 없으니깐 0이 온다.
      Bow.insert(len(word2inx)-1,1) #그러고 Bow에 (-1,1)에 추가해라 그럼 modle은 (0,1)이 되고 토큰화 된 다음 단어가 오면 (1,1)...(n,1)이 된다.
  else:
    inx = word2inx.get(word) #model이 다시 왔을 때 word2inx에 model이 이미 키값을 부여받고 존재 하니깐 여기로 오고 0값을 부여 받았으니 0값을 가져와라
    Bow[inx] +=1   #그 후 bow에 0+1을해서 증가 시키고 model은 2이 된다 또 model이 오면 3이되고 
print(word2inx) #-> 그냥 토큰화 된 것들을 0~n까지 번호를 부여된걸 보여줘라
print(Bow) #-> 빈도수를 알려줘라

## 조금 더 반복 학습과 이해가 필요함  1try

{'Model-based': 0, 'RL': 1, 'do': 2, "n't": 3, 'need': 4, 'a': 5, 'value': 6, 'function': 7, 'for': 8, 'the': 9, 'policy': 10, ',': 11, 'but': 12, 'some': 13, 'of': 14, 'algorithms': 15, 'have': 16, '.': 17}
[2, 2, 2, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


여기 까지 순서는 문장->토큰화->정제 및 추출-> 인코딩- 정수 인코딩

#5.유사도 분석
5.1 코사인 유사도

In [95]:
import numpy as np

def cos_sim(A,B):
    return np.dot(A,B) / (np.linalg.norm(A)*np.linalg.norm(B)) #np.dot-> a,b와 내적 / np.linalg.norm ->백터의 크기
a=[1,0,0,1]
b=[0,1,1,0]
c=[1,1,1,1]
print("A와B의 유사도 : ", cos_sim(a,b),'\n',"B와C의 유사도 : ",cos_sim(b,c),'\n',"A와C의 유사도 : ",cos_sim(a,c))



A와B의 유사도 :  0.0 
 B와C의 유사도 :  0.7071067811865475 
 A와C의 유사도 :  0.7071067811865475


5.2 레반슈타인 거리

In [135]:
import numpy as np
def leven (text1,text2) :  # text1,text2를 생성
  len1 =len(text1) + 1  # len1 만들기
  len2 =len(text2) + 1  # len2 만들기
  sim_array = np.zeros((len1, len2))
  sim_array[:,0] = np.linspace(0, len1-1,len1) #테이블을 생성하고 그 행 테이블에 1씩 차이나게 넣어줘라
  sim_array[0,:] = np.linspace(0, len2-1,len2) #테이블을 생성하고 그 열 테이블에 1씩 차이나게 넣어줘라
  for i in range(1,len1):
    for j in range(1,len2):
      add_char = sim_array[i,j-1] +1 #바로 위에서 +1씩 증가하게 해라 ->레반슈타인 거리 규칙 
      sub_char = sim_array[i-1,j] +1 #바로 옆에서 +1씩 증가하게 해라 ->레반슈타인 거리 규칙
      if text1[i-1] == text2[j-1]: # 수정이 되지 않았다면 대각선의 값과 동일하다
        mod_char = sim_array[i-1,j-1]
      else:
        mod_char = sim_array[i-1,j-1] + 1 #수정되었다면 +1을 해라
      sim_array[i,j] = min([add_char, sub_char, mod_char]) #상태가 수정(더하거나,빼거나,변경)할 때, 최소값을 골라서 return 해라
    return sim_array #(-1,-1)은 가장 오른쪽 끝을 나타낸다.
print(leven ('데이터마이닝','데이타마닝'))

## 값이 이상함

[[0. 1. 2. 3. 4. 5.]
 [1. 0. 1. 2. 3. 4.]
 [2. 0. 0. 0. 0. 0.]
 [3. 0. 0. 0. 0. 0.]
 [4. 0. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0.]
 [6. 0. 0. 0. 0. 0.]]
