#토큰화

우선 word_tokenize,와 WordPunctTokenizer, keras에 있는 text_to_word_sequence를 불러온다

In [ ]:
from nltk.tokenize import word_tokenize
from nltk.tokenize import WordPunctTokenizer
from tensorflow.keras.preprocessing.text import text_to_word_sequence

word_tokenize로 토큰화 해본다.

In [ ]:
import nltk
nltk.download('punkt')
print('word_tokenize 도구 이용 : ', word_tokenize("I don't care don't stop. I hate you !"))

word_tokenize 도구 이용 :  ['I', 'do', "n't", 'care', 'do', "n't", 'stop', '.', 'I', 'hate', 'you', '!']


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


결과로는 don't를 do,n't로 구분한 걸 알 수 있다.

WordPunctTokenizer로 토큰화 해본다.

In [ ]:
print('WordPunctTokenizer 도구 이용 : ', WordPunctTokenizer().tokenize("I don't care don't stop.I hate you !"))

결과로는 don't를 don,',t로 구분 한 걸 알 수 있다.


마지막으로 keras에 도구인 text_to_word_sequence로 토큰화를 해보자

In [ ]:
print('text_to_word_sequence 이용 : ', text_to_word_sequence("I don't care don't stop.I hate you !"))

text_to_word_sequence 이용 :  ['i', "don't", 'care', "don't", 'stop', 'i', 'hate', 'you']


대문자를 소문자로 바꾸고 구두점과 특수 문자를 제거 하는 것을 알 수 있다.don't를 don't로 하나의 토큰으로 인식하고 구분 한 걸 알 수 있다.

영어 문장의 경우에 특수문자를 제거하게 되면 의미가 달라질 수 있다.

그래서 표준으로 사용되고 있는 표준 토큰화인 TreebankWordTokenizer를 사용해보자

표준 토큰화 규칙

1. 하이푼으로 구성된 단어는 하나로 유지

2. doesn't와 같이 아포스트로피로'접어'가 함꼐하는 단어는 분리

In [ ]:
from nltk.tokenize import TreebankWordTokenizer
tokenizer = TreebankWordTokenizer()
text = ("Starting a home-based restaurant may be an ideal.it doesn't have a food chain or restaurant of  their own.")
print('표준 토큰화 방식 : ',tokenizer.tokenize(text))

표준 토큰화 방식 :  ['Starting', 'a', 'home-based', 'restaurant', 'may', 'be', 'an', 'ideal.it', 'does', "n't", 'have', 'a', 'food', 'chain', 'or', 'restaurant', 'of', 'their', 'own', '.']


결과를 보면 규칙을 토대로 나온 것을 알 수 있다.

nltk에서의 문장 토큰화 sent_tokenize에서 마침표가 중간 중간 있는 문장과 없는 문장을 적어보자

In [ ]:
print('중간 온점 없는 sent_tokenize : ', sent_tokenize("His barber kept his word. But keeping such a huge secret to himself was driving him crazy."))

중간 온점 없는 sent_tokenize :  ['His barber kept his word.', 'But keeping such a huge secret to himself was driving him crazy.']


In [ ]:
from nltk.tokenize import sent_tokenize
print('sent_tokenize : ',sent_tokenize("I am actively looking for Ph.D. students. and you are a Ph.D student."))

sent_tokenize :  ['I am actively looking for Ph.D. students.', 'and you are a Ph.D student.']


결과로는 NLTK는 마침표를 구분자로 문장을 구분하지 않는다라는걸 알 수 있음

NLTK와 KoNLPY를 통해서 품사 태깅 실습

In [ ]:
from nltk.tokenize import word_tokenize
from nltk.tag import pos_tag

text="I'am actively looking for Ph.D students. and you are a Ph.D. student"
tokenized_sentence = word_tokenize(text)

print("단어 태깅 : ",tokenized_sentence)
print("품사 태깅 : ",pos_tag(tokenized_sentence))

단어 태깅 :  ["I'am", 'actively', 'looking', 'for', 'Ph.D', 'students', '.', 'and', 'you', 'are', 'a', 'Ph.D.', 'student']
품사 태깅 :  [("I'am", 'NNP'), ('actively', 'RB'), ('looking', 'VBG'), ('for', 'IN'), ('Ph.D', 'NNP'), ('students', 'NNS'), ('.', '.'), ('and', 'CC'), ('you', 'PRP'), ('are', 'VBP'), ('a', 'DT'), ('Ph.D.', 'NNP'), ('student', 'NN')]


결과로는 그냥 단어만 토큰화 했을 때는 띄어쓰기 단위로 단어만 토큰화 된 것을 알 수 있지만

품사태깅을 했을 시 토큰화 된것 뒤에 품사 태깅 된것을 알 수가 있다.

In [ ]:
from konlpy.tag import Okt
from konlpy.tag import Kkma

okt = Okt()
kkma = Kkma()

print("okt 형태소 분석 : ", okt.morphs("열심히 코딩을 배운 당신, 휴식을 취해요"))
print("okt 품사 태깅 : ", okt.pos("열심히 코딩을 배운 당신, 휴식을 취해요"))
print("okt 명사 추출 : ", okt.nouns("열심히 코딩을 배운 당신, 휴식을 취해요"))
print("______________________________________________________________________________________\n")
print("kkma 형태소 분석 : ",kkma.morphs ("열심히 코딩을 배운 당신, 휴식을 취해요"))
print("kkma 품사 태깅 : ",kkma.pos("열심히 코딩을 배운 당신, 휴식을 취해요"))
print("kkma 명사 추출 : ",kkma.nouns("열심히 코딩을 배운 당신, 휴식을 취해요"))

okt 형태소 분석 :  ['열심히', '코딩', '을', '배운', '당신', ',', '휴식', '을', '취해', '요']
okt 품사 태깅 :  [('열심히', 'Adverb'), ('코딩', 'Noun'), ('을', 'Josa'), ('배운', 'Verb'), ('당신', 'Noun'), (',', 'Punctuation'), ('휴식', 'Noun'), ('을', 'Josa'), ('취해', 'Noun'), ('요', 'Josa')]
okt 명사 추출 :  ['코딩', '당신', '휴식', '취해']
______________________________________________________________________________________

kkma 형태소 분석 :  ['열심히', '코딩', '을', '배우', 'ㄴ', '당신', ',', '휴식', '을', '취하', '어요']
kkma 품사 태깅 :  [('열심히', 'MAG'), ('코딩', 'NNG'), ('을', 'JKO'), ('배우', 'VV'), ('ㄴ', 'ETD'), ('당신', 'NP'), (',', 'SP'), ('휴식', 'NNG'), ('을', 'JKO'), ('취하', 'VV'), ('어요', 'EFN')]
kkma 명사 추출 :  ['코딩', '당신', '휴식']


한글의 형태소 분석기 Okt,Kkma를 이용하여 형태소 분석 - .morphs, 품사태깅-.pos
명사 추출 - .nouns를 실행 해보았다 

#정제 및 정규화

불필요한 단어 제거

In [ ]:
import re
text = "I was wondering if anyone out there could enlighten me on this car."

#길이가 1~2인 단러들을 정규 표현식을 이용하여 삭제
shortword=re.compile(r'\w*\b\w{1,2}\b')
print(shortword.sub('',text))

 was wondering  anyone out there could enlighten   this car.


정규표현식 https://nachwon.github.io/regular-expressions/ 참고

In [ ]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

words = ['policy','doing','organization','have','going','fire','loving','love','fly','watched','has','starting']

print("표제어 추출 전 : ",words)
print("표제어 추출 후 : ",[lemmatizer.lemmatize(word)for word in words]) 

표제어 추출 전 :  ['policy', 'doing', 'organization', 'have', 'going', 'fire', 'loving', 'love', 'fly', 'watched', 'has', 'starting']
표제어 추출 후 :  ['policy', 'doing', 'organization', 'have', 'going', 'fire', 'loving', 'love', 'fly', 'watched', 'ha', 'starting']


위 결과는 ha처럼 알 수 없는 단어가 추출되었는데 이는 표제어 추출기가 본래 단어의 품사 정보를 알아야만 정확한 결과를 얻을 수 있기 때문이다.

In [ ]:
lemmatizer.lemmatize('has','v')

'have'

#불용어 제거

포터 알고리즘의 규칙
1.ALIZE -AL
2.ANCE- 제거
3.ICAL -IC

In [ ]:
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize


stemmer = PorterStemmer()

sentence= "This was not the map we found in Billy Bones's chest, but an accurate copy, complete in all things--names and heights and soundings--with the single exception of the red crosses and the written notes."
tokenized_sentence =  word_tokenize(sentence)

print("어간 추출 전 : ",tokenized_sentence)
print("어간 추출 후 : ",[stemmer.stem(word)for word in tokenized_sentence])

어간 추출 전 :  ['This', 'was', 'not', 'the', 'map', 'we', 'found', 'in', 'Billy', 'Bones', "'s", 'chest', ',', 'but', 'an', 'accurate', 'copy', ',', 'complete', 'in', 'all', 'things', '--', 'names', 'and', 'heights', 'and', 'soundings', '--', 'with', 'the', 'single', 'exception', 'of', 'the', 'red', 'crosses', 'and', 'the', 'written', 'notes', '.']
어간 추출 후 :  ['thi', 'wa', 'not', 'the', 'map', 'we', 'found', 'in', 'billi', 'bone', "'s", 'chest', ',', 'but', 'an', 'accur', 'copi', ',', 'complet', 'in', 'all', 'thing', '--', 'name', 'and', 'height', 'and', 'sound', '--', 'with', 'the', 'singl', 'except', 'of', 'the', 'red', 'cross', 'and', 'the', 'written', 'note', '.']


In [ ]:
from nltk.stem import PorterStemmer
from nltk.stem import LancasterStemmer

stemmer1 = PorterStemmer()
stemmer2 = LancasterStemmer()

words=['policy','doing','organization','have','going','love','lives','fly','dies','has']

print("어간 추출 전 : ",words)
print("포터 스태머 사용 : ",[stemmer1.stem(w)for w in words])
print("랭커스트 스태머 사용 : ",[stemmer2.stem(w)for w in words])

어간 추출 전 :  ['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'has']
포터 스태머 사용 :  ['polici', 'do', 'organ', 'have', 'go', 'love', 'live', 'fli', 'die', 'ha']
랭커스트 스태머 사용 :  ['policy', 'doing', 'org', 'hav', 'going', 'lov', 'liv', 'fly', 'die', 'has']


In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from konlpy.tag import Okt

stop_words_list=stopwords.words('english')
print("불용어 개수 : ", len(stop_words_list))
print("불용어 10개 출력 ",stop_words_list[:10])

불용어 개수 :  179
불용어 10개 출력  ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]


In [ ]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

sentence = "Family is not an important thing It's everything."
stop_words=set(stopwords.words('english'))

word_tokens = word_tokenize(sentence)

result=[]
for w in word_tokens:
  if w in stop_words:
    result.append(w)

print("불용어 제거 전 : ",word_tokens)
print("불용어 제거 후 : ",result)


불용어 제거 전 :  ['Family', 'is', 'not', 'an', 'important', 'thing', 'It', "'s", 'everything', '.']
불용어 제거 후 :  ['is', 'not', 'an']


In [ ]:
from konlpy.tag import Okt

okt = Okt()

sentence = "고기를 맘대로 굽지마. 고기 굽는 방법은 종류마다 다르고 시간도 다르다고!"
stop_words = "맘대로 방법은 다르고"

stop_words = set(stop_words.split())
word_tokens = okt.morphs(sentence)

result = [word for word in word_tokens if not word in stop_words]

print("불용어 제거 전 : ",(word_tokens))
print("불용어 제거 후 : ",(result))

불용어 제거 전 :  ['고기', '를', '맘대로', '굽지마', '.', '고기', '굽는', '방법', '은', '종류', '마다', '다르고', '시간', '도', '다르다고', '!']
불용어 제거 후 :  ['고기', '를', '굽지마', '.', '고기', '굽는', '방법', '은', '종류', '마다', '시간', '도', '다르다고', '!']


#정수 인코딩

In [32]:
import nltk
nltk.download('punkt')
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

raw_text = "A barber is a person. a barber is good person. a barber is huge person. he Knew A Secret! The Secret He Kept is huge secret. Huge secret. His barber kept his word. a barber kept his word. His barber kept his secret. But keeping and keeping such a huge secret to himself was driving the barber crazy. the barber went up a huge mountain."

#문장 토큰화
sentences= sent_tokenize(raw_text)

print(sentences)

['A barber is a person.', 'a barber is good person.', 'a barber is huge person.', 'he Knew A Secret!', 'The Secret He Kept is huge secret.', 'Huge secret.', 'His barber kept his word.', 'a barber kept his word.', 'His barber kept his secret.', 'But keeping and keeping such a huge secret to himself was driving the barber crazy.', 'the barber went up a huge mountain.']


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
import nltk
nltk.download('stopwords')
vocab = {}
preprocessed_sentences=[]
stop_words = set(stopwords.words('english'))

for sentence in sentences:
  #단어 토큰화
  tokenized_sentence = word_tokenize(sentence)
  result = []
  for word in tokenized_sentence:
    word = word.lower() #모든 단어를 소문자화하여 단어의 개수를 줄인다
    if word not in stop_words: #단어 토큰화 된 결과에 대해 불용어 제거
      if len(word) > 2: #단어 길이가 2 이하인 경우에 대하여 추가로 단어로 제거한다.
        result.append(word)
        if word not in vocab:
          vocab[word] = 0
        vocab[word] += 1
  preprocessed_sentences.append(result)
print(preprocessed_sentences)
print("_____________________________________________________________________________________________________________________________________________________________________________\n")

print(vocab)


[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]
_____________________________________________________________________________________________________________________________________________________________________________

{'barber': 8, 'person': 3, 'good': 1, 'huge': 5, 'knew': 1, 'secret': 6, 'kept': 4, 'word': 2, 'keeping': 2, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1}


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


빈도수가 높은 순서대로 sorted를 이용해서 정렬

In [ ]:
vocab_sorted = sorted(vocab.items(), key = lambda x:x[1],reverse=True)
print(vocab_sorted)

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3), ('word', 2), ('keeping', 2), ('good', 1), ('knew', 1), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)]


높은 빈도수를 가진 단어일수록 낮은 정수를 부여한다. 정수는 1부터 부여한다.

In [ ]:
word_to_index ={}
i=0
for(word,frequency)in vocab_sorted:
  if frequency > 1: #빈도수가 작은 수는 제외
    i = i + 1
    word_to_index[word]=i

print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7}


단어 집합에 존재하지 않는 단어들을 ovv(out-of-vocabulary)라고 해준다

In [ ]:
word_to_index['OOV']=len(word_to_index) +1
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7, 'OOV': 8}


정수로 인코딩 하기

In [ ]:
encoded_sentences = []
for sentence in preprocessed_sentences:
  encoded_sentence = []
  for word in sentence:
    try:
      #단어 집합에 있는 단어라면 해당 단어의 정수를 리턴.
      encoded_sentence.append(word_to_index[word])
    except KeyError:
      #만약 집합에 없는 단어라면 'oov'를 리턴
      encoded_sentence.append(word_to_index['OOV'])
  encoded_sentences.append(encoded_sentence)
print(encoded_sentences)

[[1, 5], [1, 8, 5], [1, 3, 5], [8, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 8, 1, 8], [1, 8, 3, 8]]


Counter 사용하기

In [34]:
from collections import Counter
print(preprocessed_sentences)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


단어집합을 만들기 위해서 단어를 나눠 놓은[]를 제거하고 단어들을 하나의 리스트로 만든다.

In [35]:
all_words_list=sum(preprocessed_sentences,[])
print(all_words_list)

['barber', 'person', 'barber', 'good', 'person', 'barber', 'huge', 'person', 'knew', 'secret', 'secret', 'kept', 'huge', 'secret', 'huge', 'secret', 'barber', 'kept', 'word', 'barber', 'kept', 'word', 'barber', 'kept', 'secret', 'keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy', 'barber', 'went', 'huge', 'mountain']


파이썬의 Counter()입력하여 중복을 제거하고 단어의 빈도수를 기록

In [36]:
vocab=Counter(all_words_list)
print(vocab)

Counter({'barber': 8, 'secret': 6, 'huge': 5, 'kept': 4, 'person': 3, 'word': 2, 'keeping': 2, 'good': 1, 'knew': 1, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1})


most_common()을 이용해 상위 빈도수를 가진 단어만 리턴

In [37]:
vocab_size=5
vocab=vocab.most_common(vocab_size)
vocab

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]

높은 빈도수를 가진 단어일수록 낮은 정수 인덱스를 부여한다.

In [39]:
word_to_index = {}
i=0
for(word,frequecy)in vocab:
  i = i+1
  word_to_index[word]=i

print(word_to_index)


{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


NLTK의 FreqDist사용하기

In [41]:
from nltk import FreqDist
import numpy as np
#np.hstack으로 문장구분을 제거
vocab=FreqDist(np.hstack(preprocessed_sentences))
print(vocab["barber"] )

8


In [42]:
vocab_size = 5
vocab=vocab.most_common(vocab_size)
print(vocab)

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]


In [45]:
word_to_index= {word[0]:index +1 for index,word in enumerate(vocab)}
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


케라스의 텍스트 전처리

In [48]:
from tensorflow.keras.preprocessing.text import Tokenizer

preprocessed_sentences=[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]

tokenizer = Tokenizer()

#fit_on_texts()안에 코퍼스를 입력으로 하면 빈도수를 기준으로 단어 집합을 생성한다.
tokenizer.fit_on_texts(preprocessed_sentences)

print(tokenizer.word_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7, 'good': 8, 'knew': 9, 'driving': 10, 'crazy': 11, 'went': 12, 'mountain': 13}


In [49]:
print(tokenizer.word_counts)

OrderedDict([('barber', 8), ('person', 3), ('good', 1), ('huge', 5), ('knew', 1), ('secret', 6), ('kept', 4), ('word', 2), ('keeping', 2), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)])


texts_to_sequences()는 입력으로 들어온 코퍼스에 대해서 각 단어를 이미 정해진 인덱스로 변환한다.

In [52]:
print(tokenizer.texts_to_sequences(preprocessed_sentences))

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


케라스 토크나이저에서 tokenizer=Tokenizer(num_words=숫자) == Count에서 most_common

In [58]:
vocab_size = 5
tokenizer=Tokenizer(num_words=vocab_size +1) #상위 단어 5개만 사용 +1을 해주는 이유는 num_words는 숫자 0부터 카운트하기 때문 0~4가아닌 1~5를 이용하고 싶기 때문
tokenizer.fit_on_texts(preprocessed_sentences)

print(tokenizer.word_index)
print(tokenizer.word_counts)
print(tokenizer.texts_to_sequences(preprocessed_sentences))

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7, 'good': 8, 'knew': 9, 'driving': 10, 'crazy': 11, 'went': 12, 'mountain': 13}
OrderedDict([('barber', 8), ('person', 3), ('good', 1), ('huge', 5), ('knew', 1), ('secret', 6), ('kept', 4), ('word', 2), ('keeping', 2), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)])
[[1, 5], [1, 5], [1, 3, 5], [2], [2, 4, 3, 2], [3, 2], [1, 4], [1, 4], [1, 4, 2], [3, 2, 1], [1, 3]]


케라스 토크나이저는 단어집합에 없는 단어인 oov에 대해서는 단어를 정수로 바꾸는 과정에서 아예 단어를 제거한다는 특징이 있다.
단어 집합에 없는 단어들은 oov로 간주하여 보존할려면 Tokenizer의 인자 oov_token 을 사용해야함

In [62]:
vocab_size = 5
tokenizer=Tokenizer(num_words=vocab_size +2,oov_token='OOV')
tokenizer.fit_on_texts(preprocessed_sentences)
print('단어 OOV의 인덱스 {}',format(tokenizer.word_index['OOV']))

print(tokenizer.texts_to_sequences(preprocessed_sentences))

단어 OOV의 인덱스 {} 1
[[2, 6], [2, 1, 6], [2, 4, 6], [1, 3], [3, 5, 4, 3], [4, 3], [2, 5, 1], [2, 5, 1], [2, 5, 3], [1, 1, 4, 3, 1, 2, 1], [2, 1, 4, 1]]


단어 집합이 없는 것들은 1로 인코딩 한 걸 알 수 있다.

#Padding

1.numpy로 패딩하기

1. 단어의 집합을 생성하고 그 단어를  정수 인코딩 하기

In [64]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer

preprocessed_sentences=[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(preprocessed_sentences)
encoded = tokenizer.texts_to_sequences(preprocessed_sentences)
print(encoded)

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


2.모두 동일한 길이로 맞춰주기 위해서 길이가 가장 긴 문장의 길이를 계산

In [69]:
max_len = max(len(item)for item in encoded)
print("최대 길이 : ",max_len)

최대 길이 :  7


모든 문장의 길이를 7로 맞춘다.

In [74]:
for sentence in encoded:
  while len(sentence) < max_len:
    sentence.append(0)  # 7개를 채우기 위해서 빈칸에는 0을 넣는다.

padded_np=np.array(encoded)
padded_np

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]])

빈칸을 0으로 채웠는데 이를 ZeroPadding이라고 한다.

#케라스 전처리 도구로 패딩하기

케라스에서는 패딩을 위해 pad_sequences를 지원하고 있다.


In [75]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

encoded = tokenizer.texts_to_sequences(preprocessed_sentences) # 다시 패딩 전 결과로 되돌리기
print(encoded)

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


In [76]:
padded = pad_sequences(encoded)
padded

array([[ 0,  0,  0,  0,  0,  1,  5],
       [ 0,  0,  0,  0,  1,  8,  5],
       [ 0,  0,  0,  0,  1,  3,  5],
       [ 0,  0,  0,  0,  0,  9,  2],
       [ 0,  0,  0,  2,  4,  3,  2],
       [ 0,  0,  0,  0,  0,  3,  2],
       [ 0,  0,  0,  0,  1,  4,  6],
       [ 0,  0,  0,  0,  1,  4,  6],
       [ 0,  0,  0,  0,  1,  4,  2],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 0,  0,  0,  1, 12,  3, 13]], dtype=int32)

numpy와는 다르게 pad_sequences는 기본적으로 문서의 앞에서 0을 채운다. 이때 뒤를 0으로 채우고 싶으면 ,padding='post'를 하면된다. 

In [78]:
padded = pad_sequences(encoded,padding='post')
padded

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]], dtype=int32)

,padding='post'를 하면 뒤에 0이 채워 지는 걸 볼 수 있다.

maxlen인자로 정수를 주면, 해당 정수로 모든 문서의 길이를 동일하게 할 수 있다.

In [79]:
padded = pad_sequences(encoded, padding = 'post', maxlen=5)
padded

array([[ 1,  5,  0,  0,  0],
       [ 1,  8,  5,  0,  0],
       [ 1,  3,  5,  0,  0],
       [ 9,  2,  0,  0,  0],
       [ 2,  4,  3,  2,  0],
       [ 3,  2,  0,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  2,  0,  0],
       [ 3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0]], dtype=int32)

최대 길이를 5개로 출력하고 5보다 긴 정수는 데이터가 제거 된다는 걸 알아야한다.


#원-핫 인코딩(One-Hot Encoding)

한글 형태소 분석기 Okt를 사용하여 토큰화 수행

In [86]:
from konlpy.tag import Okt

okt = Okt()
tokens = okt.morphs("나는 자연어 처리를 학습한다")
print(tokens)

['나', '는', '자연어', '처리', '를', '학습', '한다']


토큰에 고유한 정수를 부여

In [87]:
word_to_index={word : index for index, word in enumerate(tokens)}
print("단어 집합 : ",word_to_index)

단어 집합 :  {'나': 0, '는': 1, '자연어': 2, '처리': 3, '를': 4, '학습': 5, '한다': 6}


원-핫 벡터를 만들어내는 함수

In [101]:
def one_hot_encoding(word,word_to_index):
  one_hot_vector = [0]*(len(word_to_index))
  index = word_to_index[word]
  one_hot_vector[index]=1
  return one_hot_vector

"자연어"처리를 원-핫 인코딩 해보자

In [102]:
one_hot_encoding("자연어",word_to_index)

[0, 0, 1, 0, 0, 0, 0]

케라스를 이용한 원-핫 인코딩

케라스에서는 to_categorical()을 지원해서 이 도구로 원-핫 인코딩을 할 수 있다.

In [105]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

text="나랑 별 보러 가지 않을래"

tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
print("단어 집합 : ",tokenizer.word_index)

단어 집합 :  {'나랑': 1, '별': 2, '보러': 3, '가지': 4, '않을래': 5}


In [107]:
sub_text =  "별 보러 나랑 가지 않을래"
encoded = tokenizer.texts_to_sequences([sub_text])[0]
print(encoded)

[2, 3, 1, 4, 5]


In [109]:
one_hot = to_categorical(encoded)
print(one_hot)

[[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
